### ISSUE TITLE
where is tag 'v2.0'?

### ISSUE THREAD

**Issue by lzblack** [rturcios1/web-tech-project#8]

**Comment by rturcios1** [comment]
Hi Professor, I thought I was just supposed to put v2.0 in the description when I pushed my code. Is it supposed to go somewhere else? Or maybe because I pushed my code again after you sent me the hero image corrections, this got lost.

**Comment by lzblack** [comment]
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-tags#creating-a-tag

**Comment by rturcios1** [comment]
Ok I added tag v2.0 to the part I pushed the most changes and v2.1 for the push with the hero image update
